apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-worker
  namespace: prefect-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-worker
  template:
    metadata:
      labels:
        app: prefect-worker
    spec:
      serviceAccountName: prefect-worker
      containers:
        - name: prefect-worker
          image: prefecthq/prefect:3.4.11-python3.11
          command: ["/bin/bash", "-c"]
          args: 
            - |
              # Install dependencies for Kubernetes worker type
              pip install prefect-kubernetes kubernetes pyyaml
              while true; do
                prefect worker start --pool k8s-pool-k8s || true
                echo "Worker exited, restarting in 10 seconds..."
                sleep 10
              done
          env:
            - name: PREFECT_API_URL
              value: "http://prefect-server:4200/api"
            - name: PREFECT_DEPLOYMENT_NAME
              value: "my-flow/github-poc"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: token
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
